# TTGO T-Camera Plus
# D. Richards, 2022 Feb 5
# Backlight on/off
# Display
# Camera
# Camera snapshot web
# BME688
# MQTT
# ntp time

esphome:
  name: livingroom

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

# Example configuration entry
mqtt:
  broker: 192.168.178.134

ota:
  password: "c7a4e8735e45be3e4a4ce0ca4104b092"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Livingroom Fallback Hotspot"
    password: "HpZYYFyJQkJ8"

captive_portal:

output:
 platform: gpio
 id: "backlight_led"
 pin: GPIO2
 
light:
 platform: binary
 output: "backlight_led"
 name: "Backlight LED"

# Example configuration entry for ESP32
i2c:
  sda: GPIO18
  scl: GPIO23
  scan: true
  id: bus_a

bme680_bsec:

sensor:
    platform: bme680_bsec
    temperature:
      id: "temperature"
      name: "BME680 Temperature"
    pressure:
      id: "pressure"
      name: "BME680 Pressure"
    humidity:
      id: "humidity"
      name: "BME680 Humidity"
    iaq:
      id: "iaq"
      name: "BME680 IAQ"
    co2_equivalent:
      id: "co2"
      name: "BME680 CO2 Equivalent"
    breath_voc_equivalent:
      id: "voc"
      name: "BME680 Breath VOC Equivalent"

text_sensor:
  - platform: bme680_bsec
    iaq_accuracy:
      id: "accuracy"
      name: "BME680 IAQ Accuracy"


 # Example configuration entry
esp32_camera:
  name: TtGo Camera
  external_clock:
    pin: GPIO4
    frequency: 20MHz
  i2c_pins:
    sda: GPIO18
    scl: GPIO23
  data_pins: [GPIO34, GPIO13, GPIO26, GPIO35, GPIO39, GPIO38, GPIO37, GPIO36]
  vsync_pin: GPIO5
  href_pin: GPIO27
  pixel_clock_pin: GPIO25
  
  resolution: 640x480
  jpeg_quality: 10
#  aec2: true

# Example configuration entry
esp32_camera_web_server:
#  - port: 8080
#    mode: stream
  - port: 8081
    mode: snapshot
    
font:
  - file: "helvetica.ttf"
    id: helvetica_48
    size: 48
  - file: "helvetica.ttf"
    id: helvetica_24
    size: 24
  - file: "helvetica.ttf"
    id: helvetica_12
    size: 12

  # Example minimal configuration entry
spi:
  clk_pin: GPIO21
  mosi_pin: GPIO19

color:
  - id: my_red
    red: 100%
    green: 0%
    blue: 0%
  - id: my_green
    red: 0%
    green: 100%
    blue: 0%
  - id: my_blue
    red: 0%
    green: 0%
    blue: 100%
  - id: my_yellow
    red: 100%
    green: 100%
    blue: 0%

time:
  - platform: sntp
    id: esptime
    servers:
      - 0.uk.pool.ntp.org
      - 1.uk.pool.ntp.org
      - 2.uk.pool.ntp.org
      
display:
  - platform: st7789v
    backlight_pin: GPIO2
    cs_pin: GPIO12
    dc_pin: GPIO15
    reset_pin: 22 #dummy entry

    lambda: |-
      it.strftime(0,   0, id(helvetica_24),            " %H:%M:%S ", id(esptime).now());      
      it.printf  (0,  25, id(helvetica_24), my_red,    "%5.1f C",id(temperature).state);
      it.printf  (0,  50, id(helvetica_24), my_blue,   "%5.1f %%",id(humidity).state);
      it.printf  (0,  75, id(helvetica_24), my_yellow, "%5.0f CO2",id(co2).state);
      it.printf  (0, 100, id(helvetica_24), my_green,  "%5.1f VOC",id(voc).state);
      it.printf  (0, 125, id(helvetica_24),            "%5.1f IAQ",id(iaq).state);
      it.printf  (0, 150, id(helvetica_24),            " %s",id(accuracy).state.c_str());

